import { useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, Send, Check, RefreshCw } from 'lucide-react';
import { api, useSession, useWorkspace, workspaceQueryKey } from '../../../apps/dashboard/src/api.js';
import { Badge, Empty, Notice, SectionTitle } from '../../../packages/ui/src/index.js';
import type { CatalogChannel, ModuleState } from '../../../packages/module-sdk/src/browser.js';
import { eventLabels as labels, eventGroups, eventTypes, loggingSettingsSchema, type LogEvent, type LoggingEventType, type LoggingSettings } from '../shared/settings.js';

import { EventList } from './EventList.js';
import { LogPreview, type PreviewEmbed } from './LogPreview.js';

export default function LoggingPage() {
  return <><SectionTitle eyebrow="MODULES / ACTIVITY LOGGING" title="A record of the little things." description="Follow server changes, choose where they land, and keep your team in the know."/><nav className="tabs" aria-label="Logging pages">{[['', 'Events'], ['/routing', 'Routing'], ['/exclusions', 'Exclusions'], ['/retention', 'Retention'], ['/diagnostics', 'Diagnostics']].map(([path, label]) => <NavLink key={path} end to={`/modules/logging${path}`}>{label}</NavLink>)}</nav><Routes><Route index element={<Events/>}/><Route path="events/:eventId" element={<Detail/>}/><Route path="routing" element={<Configuration section="routing"/>}/><Route path="exclusions" element={<Configuration section="exclusions"/>}/><Route path="retention" element={<Configuration section="retention"/>}/><Route path="diagnostics" element={<Diagnostics/>}/><Route path="*" element={<Empty title="Page not found">Choose a logging page above.</Empty>}/></Routes></>;
}

function Events() {
  const [type, setType] = useState(''), [cursor, setCursor] = useState<string | null>(null);
  const params = new URLSearchParams({ limit: '50', ...(type ? { type } : {}), ...(cursor ? { cursor } : {}) });
  const events = useQuery({ queryKey: ['events', type, cursor], queryFn: () => api<{ events: LogEvent[]; nextCursor: string | null }>(`/api/modules/logging/events?${params}`), refetchInterval: false });
  return <section className="panel"><div className="panel-heading"><div><h2>Event stream</h2><p>Observed activity, with the context we can confirm.</p></div><label className="filter-label">Event type<select aria-label="Event type" value={type} onChange={event => { setType(event.target.value); setCursor(null); }}><option value="">All events</option>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div>{events.error && <Notice error>{events.error.message}</Notice>}{events.isPending ? <p className="loading">Loading events…</p> : <EventList events={events.data?.events ?? []}/>}<div className="list-footer"><span>Times shown in your local timezone · refresh to load newest events</span><button disabled={events.isFetching} onClick={() => { void events.refetch(); }}>Refresh events</button>{cursor && <button onClick={() => setCursor(null)}>Newest</button>}{events.data?.nextCursor && <button onClick={() => setCursor(events.data!.nextCursor)}>Older events <ArrowRight size={14}/></button>}</div></section>;
}
function Detail() {
  const { eventId } = useParams();
  const event = useQuery({ queryKey: ['event', eventId], queryFn: () => api<LogEvent>(`/api/modules/logging/events/${eventId}`) });
  const user = useSession();
  if (event.error) return <Notice error>{event.error.message}</Notice>;
  if (!event.data) return <p className="loading">Loading event…</p>;
  const data = event.data;
  return <section className="panel detail"><Link className="text-link" to="/modules/logging"><ArrowLeft size={15}/>Back to events</Link><h2>{labels[data.type]}</h2><p>{data.subjectLabel} <span className="mono">{data.subjectId}</span></p><Badge tone={data.deliveryState === 'sent' ? 'good' : 'neutral'}>{data.deliveryState ?? 'Stored'}</Badge><div className="diff-grid">{[['Before', data.before], ['After', data.after]].map(([label, value]) => <div key={String(label)}><span className="eyebrow">{String(label)}</span><pre>{value ? JSON.stringify(value, null, 2) : 'Not observed'}</pre></div>)}</div><dl><dt>Actor</dt><dd>{data.actorId ?? 'Unknown. No confirmed audit evidence.'}</dd><dt>Reason</dt><dd>{data.reason ?? 'No reason recorded'}</dd><dt>Observed</dt><dd>{new Date(data.observedAt).toLocaleString()}</dd><dt>Retention deadline</dt><dd>{new Date(data.expiresAt).toLocaleString()}</dd><dt>Configuration revision</dt><dd>{data.configRevision}</dd><dt>Event ID</dt><dd className="mono">{data.id}</dd></dl>{data.messageId && data.destinationId && !user.demo && <a className="button secondary" href={`https://discord.com/channels/${user.guildId}/${data.destinationId}/${data.messageId}`} target="_blank" rel="noreferrer">Open Discord message <ArrowRight size={15}/></a>}</section>;
}
function Configuration({ section }: { section: 'routing' | 'exclusions' | 'retention' }) {
  const user = useSession(), cache = useQueryClient();
  const workspace = useWorkspace(), state = { ...workspace, data: workspace.data?.modules.find(m => m.moduleId === 'logging') };
  const channels = useQuery({ queryKey: ['channels'], queryFn: () => api<CatalogChannel[]>('/api/catalog/channels') });
  const [draft, setDraft] = useState<LoggingSettings | null>(null), [revision, setRevision] = useState(0), [dirty, setDirty] = useState(false), [saved, setSaved] = useState(false);
  const [previewType, setPreviewType] = useState<LoggingEventType>('channel.created');
  const [preview, setPreview] = useState<PreviewEmbed | null>(null);
  useEffect(() => { if (state.data && !dirty) { setDraft(loggingSettingsSchema.parse(state.data.settings)); setRevision(state.data.desiredRevision); } }, [state.data, dirty]);
  const save = useMutation({ mutationFn: () => api<ModuleState>('/api/modules/logging/settings', 'PUT', { revision, settings: draft }), onSuccess: () => { setDirty(false); setSaved(true); void cache.invalidateQueries({ queryKey: workspaceQueryKey }); } });
  const showPreview = useMutation({ mutationFn: () => api<{ embeds: NonNullable<typeof preview>[] }>('/api/modules/logging/preview', 'POST', { settings: draft, type: previewType }), onSuccess: data => setPreview(data.embeds[0] ?? null) });
  const edit = (patch: Partial<LoggingSettings>) => { if (draft) { setDraft({ ...draft, ...patch }); setDirty(true); setSaved(false); } };
  if (state.error) return <Notice error>{state.error.message}</Notice>;
  if (!draft || !state.data) return <p className="loading">Loading configuration…</p>;
  const locked = user.access === 'viewer';
  return <div className="configuration-grid"><form className="panel settings-form" onSubmit={event => { event.preventDefault(); save.mutate(); }}><div className="panel-heading"><div><h2>{section === 'routing' ? 'Give every change a home.' : section === 'exclusions' ? 'Some spaces stay quiet.' : 'Keep what matters. Let the rest go.'}</h2><p>{section === 'routing' ? 'Choose a private text channel for server activity.' : section === 'exclusions' ? 'Excluded channels are ignored before their event metadata is stored.' : 'Set the lifetime of stored event metadata.'}</p></div></div>
    {locked && <Notice>You have read-only access. An administrator can change these settings.</Notice>}{channels.error && <Notice error>{channels.error.message}</Notice>}
    <fieldset disabled={locked || save.isPending}>{section === 'routing' && <><label>Log destination<select value={draft.destinationId ?? ''} onChange={e => edit({ destinationId: e.target.value || null })}><option value="">Select a text channel</option>{channels.data?.filter(c => c.type === 0).map(c => <option key={c.id} value={c.id}>#{c.name}{!c.canSend ? ' · permission check needed' : ''}</option>)}</select></label><small>The bot rechecks access before applying settings and sending. No channel is created automatically.</small><Notice>Enable Server Members Intent and Message Content Intent in your Discord application’s Bot settings before starting this version. Existing installations keep the new event switches off until you enable them.</Notice>{eventGroups.map(group => <section key={group.name}><h3>{group.name}</h3>{group.types.map(type => <label className="toggle-row" key={type}><span><strong>{labels[type]}</strong><small>Store the observation and queue a private log.</small></span><input type="checkbox" checked={draft.events[type]} onChange={e => edit({ events: { ...draft.events, [type]: e.target.checked } })}/></label>)}</section>)}<small>New messages do not create logs. Memory and persistent caches keep up to 5,000 recent messages for 24 hours to compare edits and recover deleted text across restarts. Messages are saved in batches; missing or unsaved content may still be unavailable. Voice moves produce a leave and a join.</small><label>Embed accent<input type="color" value={draft.accentColor} onChange={e => edit({ accentColor: e.target.value })}/></label></>}
    {section === 'exclusions' && <>{!channels.data?.length && <Empty title="No channels available">Connect the bot to populate this server’s channel catalog.</Empty>}{channels.data?.map(channel => { const key = channel.type === 4 ? 'excludedCategoryIds' : 'excludedChannelIds'; return <label className="check-row" key={channel.id}><input type="checkbox" checked={draft[key].includes(channel.id)} onChange={e => edit({ [key]: e.target.checked ? [...draft[key], channel.id] : draft[key].filter(id => id !== channel.id) })}/><span>{channel.type === 4 ? 'Category · ' : '#'}{channel.name}</span></label>; })}<small>Category exclusions cover their child channels. Previously stored metadata stays until expiry; unsent excluded events are cancelled when applied.</small></>}
    {section === 'retention' && <><label>Captured event retention<input type="number" min={7} max={90} value={draft.metadataRetentionDays} onChange={e => edit({ metadataRetentionDays: Number(e.target.value) })}/></label><small>7–90 days. Default: 30 days. Shortening retention also shortens existing event deadlines.</small><Notice>Discord log-channel history has its own lifetime. Deleting database records does not remove posts already sent to Discord.</Notice><p>Edited and deleted message text follows this retention period. Only attachment names are recorded; files are not downloaded. The temporary comparison cache clears on restart, disconnection and logging-setting changes.</p></>}
    </fieldset>{save.error && <Notice error>{save.error.message}</Notice>}{showPreview.error && <Notice error>{showPreview.error.message}</Notice>}{saved && <Notice><Check size={15}/>Saved. {state.data.appliedRevision === state.data.desiredRevision ? 'Applied by the worker.' : 'Waiting for the worker to apply this revision.'}</Notice>}{state.data.applyError && <Notice error>{state.data.applyError}</Notice>}
    <div className="form-actions"><button className="primary" type="submit" disabled={locked || save.isPending || !dirty}>{save.isPending ? 'Saving…' : 'Save settings'}</button>{section === 'routing' && <button type="button" disabled={locked || showPreview.isPending} onClick={() => showPreview.mutate()}>Preview log</button>}<span>{dirty ? 'Unsaved changes' : `Saved revision ${state.data.desiredRevision}`}</span></div></form>
    <aside className="settings-aside"><span className="eyebrow">CONFIGURATION STATUS</span><h3>A clear handoff.</h3><p>Settings are saved first, then applied by the bot. The last valid configuration stays active if a change is rejected.</p><div className="revision-row"><span>Saved</span><strong>{state.data.desiredRevision}</strong></div><div className="revision-row"><span>Applied</span><strong>{state.data.appliedRevision}</strong></div><Badge tone={state.data.applyError ? 'bad' : state.data.desiredRevision !== state.data.appliedRevision ? 'warn' : 'good'}>{state.data.applyError ? 'Needs attention' : state.data.desiredRevision !== state.data.appliedRevision ? 'Pending application' : 'Up to date'}</Badge><p>After choosing a destination, enable logging from Modules and run a test in Diagnostics.</p>{section === 'routing' && <label>Preview event<select aria-label="Preview event" value={previewType} onChange={event => { setPreviewType(event.target.value as LoggingEventType); setPreview(null); }}>{eventTypes.map(type => <option key={type} value={type}>{labels[type]}</option>)}</select></label>}{preview && <LogPreview embed={preview}/>}</aside></div>;
}
function Diagnostics() {
  const user = useSession();
  const workspace = useWorkspace(), status = { ...workspace, data: workspace.data?.status };
  const [jobId, setJobId] = useState<string | null>(null);
  const run = useMutation({ mutationFn: (type: string) => api<{ jobId: string }>(`/api/modules/logging/${type}`, 'POST', { key: crypto.randomUUID() }), onSuccess: data => setJobId(data.jobId) });
  const job = useQuery({ queryKey: ['job', jobId], queryFn: () => api<{ state: string; result: { message: string } | null; error: string | null }>(`/api/jobs/${jobId}`), enabled: !!jobId, refetchInterval: query => query.state.error || ['completed', 'failed', 'expired'].includes(query.state.data?.state ?? '') ? false : 10000 });
  return <section className="panel diagnostics"><div className="panel-heading"><div><h2>Know where things stand.</h2><p>Delivery checks run on the bot, even when the dashboard is a separate process.</p></div><Badge tone={status.data?.online ? 'good' : 'warn'}>{user.demo ? 'Simulated worker' : status.data?.online ? 'Worker connected' : 'Worker offline'}</Badge></div>{status.error && <Notice error>{status.error.message}</Notice>}<div className="diagnostic-actions"><button className="primary" disabled={user.access === 'viewer' || run.isPending} onClick={() => run.mutate('test')}><Send size={15}/>Send test log</button><button disabled={user.access === 'viewer' || run.isPending} onClick={() => run.mutate('diagnostics')}><RefreshCw size={15}/>Check destination</button></div><p>Enable logging and wait for its settings to apply first. Requests expire after five minutes; an offline bot will not post old test requests later.</p>{run.error && <Notice error>{run.error.message}</Notice>}{job.error && <Notice error>{job.error.message}</Notice>}{jobId && <Notice error={job.data?.state === 'failed'}>Job {job.data?.state ?? 'pending'}: {job.data?.error ?? job.data?.result?.message ?? 'Waiting for the worker.'}</Notice>}<h3>Recorded coverage gaps</h3>{!status.data?.incidents.length ? <Empty title="No gaps recorded">This is not a guarantee of complete coverage. Coverage includes channels, message edits/deletions, nicknames, member roles and voice joins/leaves. Offline activity and uncached previous values cannot be reconstructed.</Empty> : status.data.incidents.map(incident => <div className="incident" key={incident.id}><time>{new Date(incident.started_at).toLocaleString()}</time><p>{incident.reason}</p><small>{incident.dropped_count === null ? 'Dropped count unknown' : `${incident.dropped_count} observations not committed`}</small></div>)}</section>;
}
